use_frameworks!

platform :ios, '9.0'

target 'ZZFoundation_Example' do
  pod 'ZZFoundation', :path => '../'

  target 'ZZFoundation_Tests' do
    inherit! :search_paths
    pod 'ZZFoundation', :path => '../'
    pod 'Kiwi'
  end
end
